v2

diff --git a/.github/workflows/release2.yaml b/.github/workflows/release2.yaml
--- a/.github/workflows/release2.yaml
+++ b/.github/workflows/release2.yaml
@@ -40,64 +40,58 @@ jobs:
     strategy:
       matrix:
         goosarch:
-          - 'aix/ppc64'
-          # - 'android/386'
-          - 'android/amd64'
-          # - 'android/arm'
-          - 'android/arm64'
-          - 'darwin/amd64'
-          - 'darwin/arm64'
-          - 'dragonfly/amd64'
-          - 'freebsd/386'
-          - 'freebsd/amd64'
-          - 'freebsd/arm'
-          - 'freebsd/arm64'
-          - 'illumos/amd64'
-          # - 'ios/amd64'
-          # - 'ios/arm64'
-          - 'js/wasm'
-          - 'linux/386'
-          - 'linux/amd64'
-          - 'linux/arm'
-          - 'linux/arm64'
-          - 'linux/mips'
-          - 'linux/mips64'
-          - 'linux/mips64le'
-          - 'linux/mipsle'
-          - 'linux/ppc64'
-          - 'linux/ppc64le'
-          - 'linux/riscv64'
-          - 'linux/s390x'
-          - 'netbsd/386'
-          - 'netbsd/amd64'
-          - 'netbsd/arm'
-          - 'netbsd/arm64'
-          - 'openbsd/386'
-          - 'openbsd/amd64'
-          - 'openbsd/arm'
-          - 'openbsd/arm64'
-          - 'openbsd/mips64'
-          - 'plan9/386'
-          - 'plan9/amd64'
-          - 'plan9/arm'
-          - 'solaris/amd64'
-          - 'windows/386'
-          - 'windows/amd64'
-          - 'windows/arm'
+          - 'darwin_amd64'
+          - 'darwin_arm64'
+          - 'dragonfly_amd64'
+          - 'freebsd_386'
+          - 'freebsd_amd64'
+          - 'freebsd_arm'
+          - 'freebsd_arm64'
+          - 'linux_386'
+          - 'linux_amd64'
+          - 'linux_arm'
+          - 'linux_arm64'
+          - 'netbsd_386'
+          - 'netbsd_amd64'
+          - 'netbsd_arm'
+          - 'netbsd_arm64'
+          - 'openbsd_386'
+          - 'openbsd_amd64'
+          - 'openbsd_arm'
+          - 'openbsd_arm64'
+          - 'solaris_amd64'
+          - 'windows_386'
+          - 'windows_amd64'
+          - 'windows_arm'
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
+      - uses: actions/setup-go@v4
         with:
-          fetch-depth: 0
-      - uses: actions/setup-go@v2
-        with:
-          go-version: '1.16.3'
+          go-version: '1.18'
+      - name: Extract CLI name and version
+        run: |
+          # Get the tag name from the event payload
+          TAG_NAME=${{ github.ref_name }}
+          
+          # Use a regular expression to extract the CLI name and version
+          if [[ $TAG_NAME =~ ^([^-]+)-([^-]+)$ ]]; then
+            CLI_NAME="${BASH_REMATCH[1]}"
+            CLI_VERSION="${BASH_REMATCH[2]}"
+            
+            echo "CLI_NAME=$CLI_NAME" >> $GITHUB_ENV
+            echo "CLI_VERSION=$CLI_VERSION" >> $GITHUB_ENV
+          else
+            echo "Invalid tag format: $TAG_NAME"
+            echo "Tag should be of format CLI-VSN. e.g. ipinfo-1.0.0"
+            exit 1
+          fi
       - name: Get OS and arch info
         run: |
           GOOSARCH=${{matrix.goosarch}}
-          GOOS=${GOOSARCH%/*}
-          GOARCH=${GOOSARCH#*/}
-          BINARY_NAME=${{github.repository}}-$GOOS-$GOARCH
+          GOOS=${GOOSARCH%_*}
+          GOARCH=${GOOSARCH#*_}
+          BINARY_NAME=${{ env.CLI_NAME }}_${{ env.CLI_VERSION }}_$GOOS_$GOARCH
           echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
           echo "GOOS=$GOOS" >> $GITHUB_ENV
           echo "GOARCH=$GOARCH" >> $GITHUB_ENV
